const {test,expect}=require('@playwright/test');
for(const width of [1280,390])test(`大纲阅读与长内容换行 ${width}`,async({page})=>{
 await page.setViewportSize({width,height:900});await page.addInitScript(()=>localStorage.setItem('surveykit_tour_done','1'));
 const outline={schema_version:'surveykit.report_outline.v1',report_goal:'基于证据组织研究报告',chapters:[{chapter_no:1,title:'推荐意愿的分层全景',core_message:'NPS由用户类型、年龄、渠道共同影响',pages:[{page_no:1,page_title:'本品用户NPS显著高于非本品用户，使用本身是推荐驱动因素'.repeat(3),key_message:'需要完整显示的核心结论与证据说明。'.repeat(12),evidence_status:'sufficient',evidence_coverage:{quantitative:true},evidence_ids:['e'],suggested_visual:'LongUnbrokenLabel'.repeat(25)}]}]};
 const artifact={id:'a',type:'report_outline',title:'大纲预览验收',version:1,content:JSON.stringify(outline)};
 await page.route('**/api/research/**',async route=>{const p=new URL(route.request().url()).pathname;let result={messages:[],artifacts:[],files:[],workflows:[],datasets:[],evidence:[],insights:[],jobs:[]};if(p.endsWith('/projects'))result={projects:[{id:'reader',title:'预览验收'}]};else if(p.endsWith('/projects/reader'))result={project:{id:'reader',title:'预览验收'}};else if(p.endsWith('/artifacts'))result={artifacts:[artifact]};else if(p.endsWith('/evidence'))result={evidence:[{id:'e',claim:'证据内容'.repeat(30),strength:'strong'}]};await route.fulfill({contentType:'application/json',body:JSON.stringify(result)});});
 await page.goto('/');if(width<600)await page.locator('#mobileMenuBtn').click();await page.locator('[data-view="research"]').click();await page.locator('.research-project-card').click();if(width<600)await page.locator('[data-research-tab="artifacts"]').click();await page.locator('#researchArtifactList').getByRole('button',{name:'查看',exact:true}).click();
 const detail=page.locator('#researchArtifactDetail');await expect(detail).toBeVisible();expect(await detail.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);
 await detail.getByRole('button',{name:'展开阅读大纲'}).click();const reader=page.locator('.research-outline-reader');await expect(reader).toBeVisible();expect(await reader.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);if(width>600)expect(await reader.evaluate(el=>el.getBoundingClientRect().width)).toBeGreaterThan(900);
 await reader.locator('.research-outline-chapter').scrollIntoViewIfNeeded();await page.screenshot({path:`../outline-reader-${width}.png`});await page.keyboard.press('Escape');await expect(reader).toHaveCount(0);await expect(detail.getByRole('button',{name:'展开阅读大纲'})).toBeFocused();
});
