/** AI Researcher V0.3.1 frontend. Server /api/research is authoritative; SSE 为可选增强。 */
import { RESEARCH_RUN_RECOVERY_TIMEOUT_MS, latestStreamSnapshot, normalizeStreamPayload, parseSseBuffer, readSseResponse } from "./stream.mjs";

const API_ROOT = "/api/research";
const TYPE_LABELS = { research_plan: "调研方案", questionnaire: "定量问卷", interview_guide: "访谈大纲", other: "其他" };
const FILE_CATEGORY_LABELS = { brief: "Brief", historical_report: "历史报告", questionnaire: "问卷", interview: "访谈笔录", data: "数据", other: "其他" };
const PARSE_LABELS = { pending: "等待解析", processing: "解析中", completed: "解析完成", failed: "解析失败", unsupported: "需要人工处理" };
const state = { projects: [], project: null, messages: [], artifacts: [], files: [], selectedFileIds: new Set(), selectedArtifactId: null, activeFileId: null, activeFile: null, autoRetrieve: true, pendingArtifactContent: "", taskType: "free_chat", pollToken: 0, initialized: false, streamController: null, runRecoveryToken: 0 };
const $ = (selector) => document.querySelector(selector);

function node(tag, className, text) { const element = document.createElement(tag); if (className) element.className = className; element.textContent = text == null ? "" : String(text); return element; }
function requestId() { return globalThis.crypto?.randomUUID?.() || `research_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 9)}`; }
function formatBytes(value) { const bytes = Number(value || 0); if (bytes < 1024) return `${bytes} B`; if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`; return `${(bytes / 1024 / 1024).toFixed(1)} MB`; }
function friendlyError(status, payload) { if (status === 401 || status === 403) return "当前登录已失效，请重新登录后再试。"; if (status === 413) return payload?.error?.message || "文件或请求内容超过大小限制。"; if (status === 429) return "AI研究员请求过于频繁，请稍后再试。"; if (status === 504 || payload?.error?.type === "harness_timeout") return "AI研究员响应超时，请稍后重试。"; if ([502, 503].includes(status)) return payload?.error?.message || "AI研究员暂时无法连接，请稍后重试。"; return payload?.error?.message || payload?.message || "请求未完成，请稍后重试。"; }
async function api(path, options = {}) { const headers = { Accept: "application/json", ...(options.headers || {}) }; if (typeof options.body === "string" && !headers["Content-Type"]) headers["Content-Type"] = "application/json"; const response = await fetch(`${API_ROOT}${path}`, { credentials: "same-origin", ...options, headers }); const payload = response.status === 204 ? {} : await response.json().catch(() => ({})); if (!response.ok) { const error = new Error(friendlyError(response.status, payload)); error.status = response.status; error.retryable = Boolean(payload?.error?.retryable || [429, 502, 503, 504].includes(response.status)); throw error; } return payload?.data && typeof payload.data === "object" ? payload.data : payload; }
const jsonBody = (value) => JSON.stringify(value);
function notify(message, tone = "info", retry = null) { const box = $("#researchFeedback"); if (!box) return; box.hidden = false; box.className = `research-feedback ${tone}`; const text = node("span", "", message); box.replaceChildren(text); if (retry) { const button = node("button", "secondary-btn", "重试"); button.type = "button"; button.addEventListener("click", async () => { button.disabled = true; button.textContent = "重试中…"; box.className = "research-feedback info"; text.textContent = "正在重新连接 AI 研究员…"; try { await retry(); } catch (error) { notify(error?.message || "重试未完成，请稍后再试。", "error", retry); } }, { once: true }); box.appendChild(button); } }
function clearNotice() { const box = $("#researchFeedback"); if (box) box.hidden = true; }
function setBusy(button, busy, label = "处理中…") { if (!button) return; button.dataset.idleLabel ||= button.textContent; button.disabled = busy; button.textContent = busy ? label : button.dataset.idleLabel; }
function showMode(mode) { $("#researchHome").hidden = mode !== "home"; $("#researchCreate").hidden = mode !== "create"; $("#researchWorkspace").hidden = mode !== "workspace"; $("#researchNewProject").hidden = mode === "workspace"; }
function updatedLabel(value) { if (!value) return "刚刚更新"; const date = new Date(value); return Number.isNaN(date.valueOf()) ? "最近更新" : `更新于 ${date.toLocaleString("zh-CN", { month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" })}`; }

function renderProjects() { const list = $("#researchProjectList"); list.replaceChildren(); if (!state.projects.length) { const empty = node("div", "research-empty-state", "还没有调研项目。创建一个项目，开始与 AI 研究员协作。"); const create = node("button", "primary-btn", "＋ 新建调研项目"); create.type = "button"; create.addEventListener("click", () => showMode("create")); empty.appendChild(create); list.appendChild(empty); return; } state.projects.forEach((project) => { const card = node("button", "research-project-card", ""); card.type = "button"; const head = node("span", "research-project-card-head", ""); head.append(node("strong", "", project.title || "未命名项目"), node("span", "", project.status || "进行中")); card.append(head, node("span", "research-project-client", project.client_name || "未填写客户"), node("p", "", project.research_goal || project.brief || "尚未填写研究目标"), node("small", "", updatedLabel(project.updated_at || project.updatedAt))); card.addEventListener("click", () => openProject(project.id)); list.appendChild(card); }); }
async function loadProjects() { clearNotice(); try { const result = await api("/projects"); state.projects = result.projects || []; renderProjects(); } catch (error) { notify(error.message, "error", error.retryable ? loadProjects : null); } }
function fillProject(project) { $("#researchWorkspaceTitle").textContent = project.title || "未命名项目"; $("#researchWorkspaceMeta").textContent = [project.client_name, project.status || "进行中"].filter(Boolean).join(" · ") || "AI Researcher 工作台"; $("#researchProjectTitle").value = project.title || ""; $("#researchProjectClient").value = project.client_name || ""; $("#researchProjectBrief").value = project.brief || ""; $("#researchProjectGoal").value = project.research_goal || ""; }
function isNearBottom(list) { return list.scrollHeight - list.scrollTop - list.clientHeight < 80; }
function scrollMessagesToBottom(list) { list.scrollTop = list.scrollHeight; }
function renderMessages() { const list = $("#researchMessageList"); const shouldStick = isNearBottom(list) || list.querySelector(".research-welcome"); list.replaceChildren(); if (!state.messages.filter((item) => item.role !== "system").length) { const welcome = node("div", "research-welcome", ""); welcome.append(node("strong", "", "我是你的 AI 调研研究员。"), node("p", "", "选择当前任务需要的文件或成果，我会基于项目记忆持续协作。")); list.appendChild(welcome); return; } state.messages.forEach((message) => { if (!message || !["user", "assistant"].includes(message.role)) return; const item = node("article", `research-message ${message.role}${message.pending ? " pending" : ""}${message.error ? " error" : ""}`, ""); item.append(node("span", "research-message-role", message.role === "user" ? "你" : "AI研究员")); const content = node("div", "research-message-content", message.content || ""); if (message.streaming) content.appendChild(node("span", "research-streaming-cursor", "")); item.appendChild(content); if (message.error) item.appendChild(node("p", "research-message-state", message.error)); else if (message.pending && message.role === "user") item.appendChild(node("p", "research-message-state", "正在发送…")); else if (message.streaming) item.appendChild(node("p", "research-message-state", "正在接收回复…")); if (message.role === "assistant" && !message.streaming && !message.error && message.content) { const actions = node("div", "research-message-actions", ""); const save = node("button", "secondary-btn", "保存为新版本"); save.type = "button"; save.addEventListener("click", () => openSaveDialog(message.content || "")); actions.appendChild(save); item.appendChild(actions); } list.appendChild(item); }); if (shouldStick) scrollMessagesToBottom(list); }
async function loadMessages() { const result = await api(`/projects/${encodeURIComponent(state.project.id)}/messages`); state.messages = result.messages || []; renderMessages(); }

function artifactLabel(artifact) { return TYPE_LABELS[artifact.type] || "其他"; }
function renderArtifactDetail(artifact) { const detail = $("#researchArtifactDetail"); detail.replaceChildren(); detail.hidden = !artifact; if (!artifact) return; const head = node("div", "research-artifact-detail-head", ""); head.append(node("strong", "", artifact.title), node("span", "", `${artifactLabel(artifact)} · V${artifact.version || 1}`)); const close = node("button", "ghost-btn", "关闭"); close.type = "button"; close.addEventListener("click", () => renderArtifactDetail(null)); head.appendChild(close); const actions = node("div", "research-artifact-detail-actions", ""); const derive = node("button", "secondary-btn", "基于此版本派生"); derive.type = "button"; derive.addEventListener("click", () => selectArtifact(artifact)); actions.appendChild(derive); if (artifact.parent_artifact_id) { const compare = node("button", "ghost-btn", "与父版本对比"); compare.type = "button"; compare.addEventListener("click", () => compareArtifact(artifact)); actions.appendChild(compare); } detail.append(head, actions, node("pre", "", artifact.content || "")); }
function renderArtifacts() { const list = $("#researchArtifactList"); $("#researchArtifactCount").textContent = `${state.artifacts.length} 项`; list.replaceChildren(); if (!state.artifacts.length) { list.appendChild(node("p", "research-empty-copy", "AI 回复可保存为调研方案、问卷或访谈大纲。")); renderContextChips(); return; } state.artifacts.forEach((artifact) => { const card = node("article", `research-artifact-card${state.selectedArtifactId === artifact.id ? " selected" : ""}`, ""); const meta = node("div", "research-artifact-meta", ""); meta.append(node("span", "", artifactLabel(artifact)), node("strong", "", `V${artifact.version || 1}`)); card.append(meta, node("h5", "", artifact.title || artifactLabel(artifact))); if (artifact.parent_artifact_id) card.append(node("small", "research-version-parent", "基于上一版本生成")); const actions = node("div", "research-artifact-actions", ""); [["查看", () => renderArtifactDetail(artifact)], ["基于此版本派生", () => selectArtifact(artifact)], ["重命名", () => renameArtifact(artifact)], ["删除", () => deleteArtifact(artifact)]].forEach(([label, action], index) => { const button = node("button", index === 1 ? "secondary-btn" : "ghost-btn", label); button.type = "button"; button.addEventListener("click", action); actions.appendChild(button); }); card.appendChild(actions); list.appendChild(card); }); renderContextChips(); }
async function compareArtifact(artifact) { const detail = $("#researchArtifactDetail"); try { const result = await api(`/projects/${encodeURIComponent(state.project.id)}/artifacts/${encodeURIComponent(artifact.id)}/compare`); const comparison = result.comparison; const panel = node("section", "research-artifact-diff", ""); panel.append(node("strong", "", `V${comparison.base.version} → V${comparison.target.version}：新增 ${comparison.summary.added} 行，删除 ${comparison.summary.removed} 行`)); const changes = node("pre", "", ""); changes.replaceChildren(...comparison.changes.filter((change) => change.type !== "unchanged").slice(0, 160).map((change) => node("span", change.type, `${change.type === "added" ? "+" : "−"} ${change.text}\n`))); panel.appendChild(changes); detail.querySelector(".research-artifact-diff")?.remove(); detail.appendChild(panel); } catch (error) { notify(error.message, "error"); } }
async function loadArtifacts() { const result = await api(`/projects/${encodeURIComponent(state.project.id)}/artifacts`); state.artifacts = result.artifacts || []; if (state.selectedArtifactId && !state.artifacts.some((artifact) => artifact.id === state.selectedArtifactId)) state.selectedArtifactId = null; renderArtifacts(); }

function fileStatus(file) { return PARSE_LABELS[file.parse_status] || file.parse_status || "未知状态"; }
function renderFiles() { const list = $("#researchFileList"); $("#researchFileCount").textContent = `${state.files.length} 个文件`; list.replaceChildren(); if (!state.files.length) list.appendChild(node("p", "research-empty-copy", "还没有项目文件。上传后可按需加入 AI 上下文。")); state.files.forEach((file) => { const button = node("button", `research-file-item status-${file.parse_status}${state.selectedFileIds.has(file.id) ? " selected" : ""}`, ""); button.type = "button"; const copy = node("span", "research-file-item-copy", ""); copy.append(node("strong", "", file.file_name), node("small", "", `${FILE_CATEGORY_LABELS[file.category] || "其他"} · ${formatBytes(file.file_size)}`)); button.append(copy, node("span", "research-file-status", fileStatus(file))); button.addEventListener("click", () => openFile(file.id)); list.appendChild(button); }); renderContextChips(); }
async function loadFiles({ poll = true } = {}) { const result = await api(`/projects/${encodeURIComponent(state.project.id)}/files`); state.files = result.files || []; for (const id of [...state.selectedFileIds]) if (!state.files.some((file) => file.id === id)) state.selectedFileIds.delete(id); renderFiles(); if (poll && state.files.some((file) => ["pending", "processing"].includes(file.parse_status) || file.ocr_status === "processing")) { const token = ++state.pollToken; setTimeout(() => { if (state.project && token === state.pollToken) loadFiles({ poll: true }).catch(() => {}); }, 1200); } }
async function uploadFiles(fileList) { if (!state.project || !fileList?.length) return; const button = $("#researchUploadFile"); setBusy(button, true, "上传中…"); clearNotice(); try { for (const file of [...fileList]) await api(`/projects/${encodeURIComponent(state.project.id)}/files`, { method: "POST", headers: { "Content-Type": file.type || "application/octet-stream", "X-Research-File-Name": encodeURIComponent(file.name), "X-Research-File-Category": "other" }, body: file }); $("#researchFileInput").value = ""; await loadFiles(); notify("文件已上传，后台正在解析。", "success"); } catch (error) { notify(error.message, "error"); } finally { setBusy(button, false); } }
function structureSummary(structure) { if (structure?.kind !== "xlsx_workbook") return ""; return (structure.sheets || []).map((sheet) => `${sheet.name} · ${sheet.row_count} 行 × ${sheet.column_count} 列\n字段：${(sheet.fields || []).join("、") || "未识别"}\n预览：\n${(sheet.preview_rows || []).map((row) => row.join(" | ")).join("\n") || "无"}`).join("\n\n"); }
async function openFile(fileId) { try { const result = await api(`/projects/${encodeURIComponent(state.project.id)}/files/${encodeURIComponent(fileId)}`); const file = result.file; state.activeFileId = file.id; state.activeFile = file; $("#researchFileDialogTitle").textContent = file.file_name; $("#researchFileDialogMeta").textContent = `${file.file_type.toUpperCase()} · ${formatBytes(file.file_size)} · ${fileStatus(file)} · ${updatedLabel(file.created_at)}`; $("#researchFileCategory").value = file.category || "other"; $("#researchFileSummary").textContent = file.summary || file.parse_note || "暂无摘要"; $("#researchFilePreview").textContent = file.preview || file.parse_note || "暂无可预览内容"; const structured = structureSummary(file.structured_data); $("#researchFileStructure").hidden = !structured; $("#researchFileStructurePreview").textContent = structured; const ocr = $("#researchFileOcr"); ocr.hidden = file.file_type !== "pdf"; ocr.disabled = file.ocr_status === "processing"; ocr.textContent = file.ocr_status === "processing" ? "OCR 处理中…" : "按需 OCR"; $("#researchFileOcrState").textContent = file.ocr_note || ""; $("#researchFileDialog").showModal(); } catch (error) { notify(error.message, "error"); } }
async function updateFileCategory() { if (!state.activeFileId) return; try { await api(`/projects/${state.project.id}/files/${state.activeFileId}`, { method: "PATCH", body: jsonBody({ category: $("#researchFileCategory").value }) }); await loadFiles({ poll: false }); } catch (error) { notify(error.message, "error"); } }
async function reparseFile() { if (!state.activeFileId) return; try { await api(`/projects/${state.project.id}/files/${state.activeFileId}/reparse`, { method: "POST", body: jsonBody({}) }); $("#researchFileDialog").close(); await loadFiles(); notify("文件已进入重新解析队列。", "success"); } catch (error) { notify(error.message, "error"); } }
async function requestOcr() { if (!state.activeFileId) return; const button = $("#researchFileOcr"); setBusy(button, true, "提交中…"); try { await api(`/projects/${state.project.id}/files/${state.activeFileId}/ocr`, { method: "POST", body: jsonBody({}) }); $("#researchFileDialog").close(); await loadFiles(); notify("PDF 已进入 OCR 队列。", "success"); } catch (error) { notify(error.message, "error"); } finally { setBusy(button, false); } }
async function deleteFile() { if (!state.activeFileId || !window.confirm("删除这个项目文件吗？")) return; const fileId = state.activeFileId; try { await api(`/projects/${state.project.id}/files/${fileId}`, { method: "DELETE" }); state.selectedFileIds.delete(fileId); state.activeFileId = null; $("#researchFileDialog").close(); await loadFiles({ poll: false }); notify("文件已删除。", "success"); } catch (error) { notify(error.message, "error"); } }

function renderContextChips() { const box = $("#researchContextChips"); if (!box) return; box.replaceChildren(); if (state.autoRetrieve) box.appendChild(node("span", "research-context-chip memory", "⌕ 自动检索项目记忆")); state.files.filter((file) => state.selectedFileIds.has(file.id)).forEach((file) => { const chip = node("span", "research-context-chip file", `📄 ${file.file_name}`); const remove = node("button", "", "×"); remove.type = "button"; remove.setAttribute("aria-label", `移除 ${file.file_name}`); remove.addEventListener("click", () => { state.selectedFileIds.delete(file.id); renderContextChips(); renderFiles(); }); chip.appendChild(remove); box.appendChild(chip); }); const artifact = state.artifacts.find((item) => item.id === state.selectedArtifactId); if (artifact) { const chip = node("span", "research-context-chip artifact", `📋 ${artifact.title} V${artifact.version}`); const remove = node("button", "", "×"); remove.type = "button"; remove.addEventListener("click", clearArtifactContext); chip.appendChild(remove); box.appendChild(chip); } if (!box.children.length) box.appendChild(node("span", "research-context-empty", "仅使用项目基础信息")); }
function openContextDialog() { $("#researchAutoRetrieve").checked = state.autoRetrieve; $("#researchMemoryResults").replaceChildren(node("p", "research-empty-copy", "可先检索，查看系统会匹配到哪些项目片段。")); const fileOptions = $("#researchContextFileOptions"); fileOptions.replaceChildren(); if (!state.files.length) fileOptions.appendChild(node("p", "research-empty-copy", "暂无项目文件")); state.files.forEach((file) => { const label = node("label", "research-context-option", ""); const input = document.createElement("input"); input.type = "checkbox"; input.value = file.id; input.checked = state.selectedFileIds.has(file.id); input.disabled = file.parse_status !== "completed"; label.append(input, node("span", "", `${file.file_name} · ${fileStatus(file)}`)); fileOptions.appendChild(label); }); const artifactOptions = $("#researchContextArtifactOptions"); artifactOptions.replaceChildren(); const noneLabel = node("label", "research-context-option", ""); const none = document.createElement("input"); none.type = "radio"; none.name = "research-context-artifact"; none.value = ""; none.checked = !state.selectedArtifactId; noneLabel.append(none, node("span", "", "不使用成果")); artifactOptions.appendChild(noneLabel); state.artifacts.forEach((artifact) => { const label = node("label", "research-context-option", ""); const input = document.createElement("input"); input.type = "radio"; input.name = "research-context-artifact"; input.value = artifact.id; input.checked = state.selectedArtifactId === artifact.id; label.append(input, node("span", "", `${artifact.title} · V${artifact.version}`)); artifactOptions.appendChild(label); }); $("#researchContextDialog").showModal(); }
async function searchMemory() { const query = $("#researchMemoryQuery").value.trim(); if (!query) return; const box = $("#researchMemoryResults"); box.replaceChildren(node("p", "research-empty-copy", "检索中…")); try { const result = await api(`/projects/${encodeURIComponent(state.project.id)}/memory/search?q=${encodeURIComponent(query)}`); box.replaceChildren(); if (!result.matches?.length) box.appendChild(node("p", "research-empty-copy", "没有找到相关片段。")); for (const match of result.matches || []) { const item = node("article", "research-memory-result", ""); item.append(node("strong", "", match.file_name), node("small", "", `${match.heading || `片段 ${match.chunk_index + 1}`} · 相关度 ${Math.round(match.score)}`), node("p", "", match.content)); box.appendChild(item); } } catch (error) { box.replaceChildren(node("p", "research-empty-copy", error.message)); } }
function applyContext(event) { event.preventDefault(); state.autoRetrieve = $("#researchAutoRetrieve").checked; state.selectedFileIds = new Set([...document.querySelectorAll('#researchContextFileOptions input[type="checkbox"]:checked')].map((input) => input.value).slice(0, 8)); state.selectedArtifactId = document.querySelector('input[name="research-context-artifact"]:checked')?.value || null; state.taskType = state.selectedArtifactId ? "artifact_revision" : state.taskType; $("#researchContextDialog").close(); renderContextChips(); renderFiles(); renderArtifacts(); }

async function openProject(projectId) { clearNotice(); showMode("workspace"); setMobileTab("chat"); state.pollToken += 1; state.selectedFileIds.clear(); state.selectedArtifactId = null; state.taskType = "free_chat"; try { const result = await api(`/projects/${encodeURIComponent(projectId)}`); state.project = result.project || result; fillProject(state.project); await Promise.all([loadMessages(), loadArtifacts(), loadFiles()]); } catch (error) { notify(error.message, "error", error.retryable ? () => openProject(projectId) : null); } }
async function createProject(event) { event.preventDefault(); const button = $("#researchCreateSubmit"); const body = { title: $("#researchCreateTitle").value.trim(), client_name: $("#researchCreateClient").value.trim(), brief: $("#researchCreateBrief").value.trim(), research_goal: $("#researchCreateGoal").value.trim() }; if (!body.title) return; setBusy(button, true, "创建中…"); try { const result = await api("/projects", { method: "POST", body: jsonBody(body) }); $("#researchCreateForm").reset(); await loadProjects(); await openProject((result.project || result).id); } catch (error) { notify(error.message, "error"); } finally { setBusy(button, false); } }
async function updateProject(event) { event.preventDefault(); const button = $("#researchSaveProject"); const body = { title: $("#researchProjectTitle").value.trim(), client_name: $("#researchProjectClient").value.trim(), brief: $("#researchProjectBrief").value.trim(), research_goal: $("#researchProjectGoal").value.trim() }; setBusy(button, true, "保存中…"); try { const result = await api(`/projects/${encodeURIComponent(state.project.id)}`, { method: "PATCH", body: jsonBody(body) }); state.project = result.project || result; fillProject(state.project); $("#researchProjectSaveState").textContent = "刚刚保存"; } catch (error) { notify(error.message, "error"); } finally { setBusy(button, false); } }
function setConnectionState(text, mode = "ready") { const badge = $("#researchConnectionState"); if (!badge) return; badge.textContent = text; badge.dataset.state = mode; }
function normalizeAssistantResult(result) { return result?.message?.role === "assistant" ? result.message : result?.reply ? { role: "assistant", content: result.reply } : null; }
function applyMessageResult(result) { const assistant = normalizeAssistantResult(result); const applied = result?.applied_context; setConnectionState(applied ? `显式 ${applied.selected_files?.length || 0} 个文件 · 检索 ${applied.retrieved_chunks?.length || 0} 个片段` : "会话已同步", "ready"); return assistant; }
function streamRunId(payload) { return String(payload?.run_id || payload?.runId || payload?.id || ""); }
async function responseError(response) {
  const payload = await response.json().catch(() => ({}));
  const error = new Error(friendlyError(response.status, payload));
  error.status = response.status;
  error.retryable = Boolean(payload?.error?.retryable || [429, 502, 503, 504].includes(response.status));
  return error;
}
async function postMessage(body, { onDelta, onProgress } = {}) {
  const response = await fetch(`${API_ROOT}/projects/${encodeURIComponent(state.project.id)}/messages`, { method: "POST", credentials: "same-origin", headers: { Accept: "text/event-stream, application/json", "Content-Type": "application/json" }, body: jsonBody(body) });
  const contentType = response.headers.get("content-type") || "";
  if (contentType.includes("text/event-stream")) {
    if (!response.ok) throw await responseError(response);
    let runId = "";
    const rememberRun = (payload) => { runId ||= streamRunId(payload); };
    let read;
    try {
      read = await readSseResponse(response, { onDelta, onProgress });
    } catch (error) {
      error.runId ||= runId;
      throw error;
    }
    read.events.forEach((event) => rememberRun(event.payload));
    return { streamed: true, result: read.result, partialContent: read.partialContent, runId: runId || streamRunId(read.result) };
  }
  const payload = response.status === 204 ? {} : await response.json().catch(() => ({}));
  if (!response.ok) { const error = new Error(friendlyError(response.status, payload)); error.status = response.status; error.retryable = Boolean(payload?.error?.retryable || [429, 502, 503, 504].includes(response.status)); throw error; }
  return { streamed: false, result: payload?.data && typeof payload.data === "object" ? payload.data : payload };
}

function failPendingMessage(body, error, partial = "", wasRetry = false) {
  state.messages.forEach((item) => { if (item.id === body.client_request_id) item.pending = false; });
  state.messages = state.messages.filter((item) => ![`${body.client_request_id}-stream`, `${body.client_request_id}-partial`].includes(item.id));
  if (partial) state.messages.push({ id: `${body.client_request_id}-partial`, role: "assistant", content: partial, error: "连接中断，以上为已接收的部分回复。" });
  renderMessages();
  setConnectionState("连接失败", "error");
  notify(`${wasRetry ? "重试未成功：" : ""}${error.message}`, "error", error.retryable ? () => sendMessage(null, body) : null);
}
async function recoverRun(runId, onProgress) {
  const deadline = Date.now() + RESEARCH_RUN_RECOVERY_TIMEOUT_MS;
  let delay = 800;
  while (Date.now() < deadline) {
    const { run } = await api(`/projects/${encodeURIComponent(state.project.id)}/runs/${encodeURIComponent(runId)}`);
    if (run?.partial_content) onProgress?.(run.partial_content);
    if (run?.status === "completed" && run.result) return run.result;
    if (run?.status === "failed") { const error = new Error(run.error?.message || "AI研究员运行失败。"); error.retryable = Boolean(run.error?.retryable); throw error; }
    await new Promise((resolve) => setTimeout(resolve, delay));
    delay = Math.min(2_000, Math.round(delay * 1.35));
  }
  const error = new Error("连接中断，后台任务仍在运行，请稍后重试以同步结果。"); error.retryable = true; throw error;
}
async function sendMessage(event, retryBody = null) {
  event?.preventDefault?.();
  if (!state.project) return;
  const input = $("#researchChatInput");
  const body = retryBody || { message: input.value.trim(), artifact_id: state.selectedArtifactId || undefined, selected_file_ids: [...state.selectedFileIds], auto_retrieve: state.autoRetrieve, task_type: state.taskType, client_request_id: requestId() };
  if (!body.message) return;
  if (!retryBody) clearNotice();
  if (!retryBody) {
    state.messages.push({ id: body.client_request_id, role: "user", content: body.message, pending: true });
    input.value = "";
    renderMessages();
  }
  const button = $("#researchSendMessage");
  setBusy(button, true, "AI思考中…");
  setConnectionState(retryBody ? "正在重试" : "正在连接", "connecting");
  let streamedText = "";
  const renderStreamingAssistant = (content) => {
    let assistant = state.messages.find((item) => item.id === `${body.client_request_id}-stream`);
    if (!assistant) { assistant = { id: `${body.client_request_id}-stream`, role: "assistant", content: "", streaming: true }; state.messages.push(assistant); }
    assistant.content = content;
    renderMessages();
    setConnectionState("正在接收回复", "streaming");
  };
  try {
    const { streamed, result, partialContent, runId } = await postMessage(body, {
      onDelta: (delta) => { streamedText += delta; renderStreamingAssistant(streamedText); },
      onProgress: (snapshot) => { streamedText = snapshot; renderStreamingAssistant(streamedText); },
    });
    streamedText = partialContent || streamedText;
    await loadMessages();
    if (result) {
      state.messages = state.messages.filter((item) => item.id !== `${body.client_request_id}-stream`);
      const assistant = applyMessageResult(result);
      if (assistant && !state.messages.some((item) => item.id && item.id === assistant.id)) state.messages.push(assistant);
      renderMessages();
    } else if (streamed) {
      state.messages = state.messages.filter((item) => item.id !== `${body.client_request_id}-stream`);
      if (streamedText) state.messages.push({ id: `${body.client_request_id}-partial`, role: "assistant", content: streamedText, error: "已接收部分回复；可重试以同步完整结果。" });
      setConnectionState("已接收部分回复，等待同步", "streaming");
      renderMessages();
    }
    clearNotice();
  } catch (error) {
    if (error.runId) {
      try {
        const result = await recoverRun(error.runId, (snapshot) => { streamedText = snapshot; renderStreamingAssistant(streamedText); });
        await loadMessages();
        state.messages = state.messages.filter((item) => item.id !== `${body.client_request_id}-stream`);
        const assistant = applyMessageResult(result);
        if (assistant && !state.messages.some((item) => item.id && item.id === assistant.id)) state.messages.push(assistant);
        renderMessages(); clearNotice();
      } catch (recoveryError) { failPendingMessage(body, recoveryError, streamedText, Boolean(retryBody)); }
    } else failPendingMessage(body, error, streamedText, Boolean(retryBody));
  } finally {
    setBusy(button, false);
    input.focus();
  }
}

function openSaveDialog(content) { state.pendingArtifactContent = content; const title = content.split(/\r?\n/).map((line) => line.replace(/^#+\s*/, "").trim()).find(Boolean) || "AI 研究成果"; $("#researchArtifactTitle").value = title.slice(0, 120); const parent = state.artifacts.find((artifact) => artifact.id === state.selectedArtifactId); if (parent) $("#researchArtifactType").value = parent.type; $("#researchSaveArtifactDialog").showModal(); }
async function saveArtifact(event) { event.preventDefault(); const body = { title: $("#researchArtifactTitle").value.trim(), type: $("#researchArtifactType").value, content: state.pendingArtifactContent, parent_artifact_id: state.selectedArtifactId || undefined }; try { const result = await api(`/projects/${encodeURIComponent(state.project.id)}/artifacts`, { method: "POST", body: jsonBody(body) }); $("#researchSaveArtifactDialog").close(); state.pendingArtifactContent = ""; state.selectedArtifactId = (result.artifact || result).id; await loadArtifacts(); notify("成果已保存为新版本。", "success"); } catch (error) { notify(error.message, "error"); } }
function selectArtifact(artifact) { state.selectedArtifactId = artifact.id; state.taskType = "artifact_revision"; $("#researchChatInput").value = "请基于这份成果继续修改："; setMobileTab("chat"); renderContextChips(); renderArtifacts(); $("#researchChatInput").focus(); }
function clearArtifactContext() { state.selectedArtifactId = null; if (state.taskType === "artifact_revision") state.taskType = "free_chat"; renderContextChips(); renderArtifacts(); }
async function renameArtifact(artifact) { const title = window.prompt("输入新的成果名称", artifact.title || ""); if (!title?.trim()) return; try { await api(`/projects/${state.project.id}/artifacts/${artifact.id}`, { method: "PATCH", body: jsonBody({ title: title.trim() }) }); await loadArtifacts(); } catch (error) { notify(error.message, "error"); } }
async function deleteArtifact(artifact) { if (!window.confirm(`删除“${artifact.title}”吗？`)) return; try { await api(`/projects/${state.project.id}/artifacts/${artifact.id}`, { method: "DELETE" }); if (state.selectedArtifactId === artifact.id) clearArtifactContext(); renderArtifactDetail(null); await loadArtifacts(); } catch (error) { notify(error.message, "error"); } }
function setMobileTab(tab) { document.querySelectorAll("[data-research-tab]").forEach((button) => { const active = button.dataset.researchTab === tab; button.classList.toggle("active", active); button.setAttribute("aria-selected", String(active)); }); document.querySelectorAll("[data-research-panel]").forEach((panel) => panel.classList.toggle("active", panel.dataset.researchPanel === tab)); }
function bindEvents() { $("#researchNewProject")?.addEventListener("click", () => showMode("create")); $("#researchCreateCancel")?.addEventListener("click", () => showMode("home")); $("#researchCreateForm")?.addEventListener("submit", createProject); $("#researchRefreshProjects")?.addEventListener("click", loadProjects); $("#researchBackToProjects")?.addEventListener("click", async () => { state.pollToken += 1; state.project = null; state.selectedFileIds.clear(); clearArtifactContext(); showMode("home"); await loadProjects(); }); $("#researchContextForm")?.addEventListener("submit", updateProject); $("#researchChatForm")?.addEventListener("submit", sendMessage); $("#researchUploadFile")?.addEventListener("click", () => $("#researchFileInput").click()); $("#researchFileInput")?.addEventListener("change", (event) => uploadFiles(event.target.files)); $("#researchFileCategory")?.addEventListener("change", updateFileCategory); $("#researchFileReparse")?.addEventListener("click", reparseFile); $("#researchFileOcr")?.addEventListener("click", requestOcr); $("#researchFileDelete")?.addEventListener("click", deleteFile); $("#researchFileClose")?.addEventListener("click", () => $("#researchFileDialog").close()); $("#researchAddContext")?.addEventListener("click", openContextDialog); $("#researchMemorySearch")?.addEventListener("click", searchMemory); $("#researchContextPickerForm")?.addEventListener("submit", applyContext); $("#researchContextCancel")?.addEventListener("click", () => $("#researchContextDialog").close()); $("#researchSaveArtifactForm")?.addEventListener("submit", saveArtifact); $("#researchArtifactCancel")?.addEventListener("click", () => { state.pendingArtifactContent = ""; $("#researchSaveArtifactDialog").close(); }); $("#researchQuickTasks")?.addEventListener("click", (event) => { const button = event.target.closest("[data-research-prompt]"); if (!button) return; state.taskType = button.dataset.researchTaskType || "free_chat"; $("#researchChatInput").value = button.dataset.researchPrompt; $("#researchChatInput").focus(); }); document.querySelectorAll("[data-research-tab]").forEach((button) => button.addEventListener("click", () => setMobileTab(button.dataset.researchTab))); document.querySelector('[data-view="research"]')?.addEventListener("click", () => { showMode(state.project ? "workspace" : "home"); if (!state.project) loadProjects(); }); }
export function initAiResearcher() { if (state.initialized || !$("#research")) return; state.initialized = true; bindEvents(); showMode("home"); renderProjects(); if (window.location.hash === "#research") loadProjects(); }
export const researchApi = { api };
export const researchStreaming = { latestStreamSnapshot, normalizeStreamPayload, parseSseBuffer, readSseResponse };
